server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization_grant_type : authorization_code
            client-id : oauth2-client-app
            client-name : oauth2-client-app
            client-secret : eJuzZoD8ytxnbrT5FIBqLPftdhH2yUPf
            redirect-uri : http://localhost:8000/login/oauth2/code/keycloak
            clientAuthenticationMethod : client_secret_post
            scope : openid
        provider:
          keycloak:
            authorization-uri : http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri : http://localhost:8080/realms/oauth2